services:
  web:
    build:
      context: .
    image: localhost:7002/acnhmate-web:${TAG}
    container_name: ${WEB_CONTAINER}
    restart: always
    ports:
      - ${WEB_PORT}:80
    environment:
      - API_URL=http://20.223.239.183:${API_PORT}